project:
  type: book

book:
  title: "Accounting Analytics"
  author: "Mauricio Codesso"
  date: "3/30/2026"
  chapters:
    - index.md
    - 00_preface.md
    - 01_chapter.md
  sidebar:
    contents:
      - text: "Preface"
        href: 00_preface.md
      - text: "The Role of Analytics in Accounting"
        href: 01_chapter.md

format:
  html:
    theme:
      - cosmo
      - styles/book.scss
    toc: true
    toc-depth: 2
    fig-cap-location: bottom
    tbl-cap-location: top
    link-external-newwindow: true
    number-sections: true
  pdf:
    documentclass: scrreprt
    include-in-header: styles/book-pdf.tex
    colorlinks: true
    fig-cap-location: bottom
    tbl-cap-location: top

crossref:
  fig-title: Figure
  tbl-title: Table
