project:
  type: book

book:
  title: "Accounting Analytics: A Practical Approach"
  author: "Mauricio Codesso"
  date: "3/30/2026"
  chapters:
    - index.md
    - intro.md


bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



