project:
  type: book

book:
  title: "Accounting Analytics: A Practical Approach"
  author: "Mauricio Codesso"
  date: "3/30/2026"
  chapters:
    - index.md
    - chapter_01.md

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - styles/book.scss
    toc: true
    toc-depth: 3
    fig-cap-location: bottom
    tbl-cap-location: top
    link-external-newwindow: true
  pdf:
    documentclass: scrreprt
    include-in-header: styles/book-pdf.tex
    colorlinks: true
    fig-cap-location: bottom
    tbl-cap-location: top

crossref:
  fig-title: Figure
  tbl-title: Table
